# Generated by Django 4.1.4 on 2023-04-06 03:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='数据源id')),
                ('data_source_name', models.CharField(max_length=255, unique=True, verbose_name='数据源名称')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip地址')),
                ('port', models.PositiveSmallIntegerField(verbose_name='端口')),
                ('user_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('pass_word', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('db_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='数据库名称')),
                ('data_source_url', models.CharField(max_length=500, verbose_name='数据源链接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('extend', models.JSONField(blank=True, null=True, verbose_name='扩展属性')),
            ],
            options={
                'verbose_name': '数据源管理',
                'verbose_name_plural': '数据源管理',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceTable',
            fields=[
                ('table_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='表编码')),
                ('table_name_zh', models.CharField(blank=True, max_length=255, null=True, verbose_name='表显示名')),
                ('table_name_en', models.CharField(max_length=255, verbose_name='表物理名')),
                ('table_logical_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='逻辑表名')),
                ('table_sort_id', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('table_data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_tools.datasource', verbose_name='数据源名称')),
            ],
            options={
                'verbose_name': '表管理',
                'verbose_name_plural': '表管理',
                'ordering': ['table_sort_id', '-update_time'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source_type_name', models.CharField(max_length=255, unique=True, verbose_name='数据源类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据源类型',
                'verbose_name_plural': '数据源类型',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ThemeDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='目录名称')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='data_tools.themedirectory', verbose_name='上级目录')),
            ],
            options={
                'verbose_name': '目录管理',
                'verbose_name_plural': '目录管理',
            },
        ),
        migrations.CreateModel(
            name='DirectoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_name_table', to='data_tools.themedirectory', verbose_name='目录')),
                ('table_name_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_tools.datasourcetable', verbose_name='表名称')),
            ],
            options={
                'verbose_name': '目录关联管理',
                'verbose_name_plural': '目录关联管理',
            },
        ),
        migrations.CreateModel(
            name='DataSourceTableField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name_cn', models.CharField(blank=True, max_length=64, null=True, verbose_name='字段显示名')),
                ('column_name_en', models.CharField(max_length=64, verbose_name='字段物理名')),
                ('column_type', models.CharField(choices=[('char', 'char'), ('varchar', 'varchar'), ('int', 'int'), ('text', 'text'), ('date', 'date'), ('timestamp', 'timestamp'), ('float', 'float'), ('bool', 'bool'), ('jsonb', 'jsonb')], default='varchar', max_length=32, verbose_name='字段类型')),
                ('column_length', models.CharField(max_length=32, verbose_name='字段长度')),
                ('ordinal_position', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('column_is_pk', models.BooleanField(default=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_list_show', models.BooleanField(default=False, verbose_name='列表显示')),
                ('is_detail_show', models.BooleanField(default=False, verbose_name='详情显示')),
                ('table_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_fields', to='data_tools.datasourcetable', verbose_name='表物理名')),
            ],
            options={
                'verbose_name': '字段管理',
                'verbose_name_plural': '字段管理',
                'ordering': ['ordinal_position', 'create_time'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_tools.datasourcetype', to_field='data_source_type_name'),
        ),
    ]
