# Generated by Django 4.1.4 on 2023-03-30 04:59

import apps.users.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mugshot',
            field=imagekit.models.fields.ProcessedImageField(upload_to=apps.users.models.user_mugshot_path, verbose_name='头像'),
        ),
    ]
