# Generated by Django 4.1.4 on 2023-04-06 03:06

import apps.extension_tools.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='链接名字')),
                ('link_url', models.URLField(max_length=100, verbose_name='链接网址')),
                ('link_img', imagekit.models.fields.ProcessedImageField(upload_to=apps.extension_tools.models.user_mugshot_path, verbose_name='封面图片')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '友链接',
                'verbose_name_plural': '友链接',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='公告内容')),
                ('level', models.CharField(choices=[('sticky', '置顶'), ('latest', '最新'), ('ordinary', '一般')], default='最新', max_length=30)),
                ('release_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '网站公告',
                'verbose_name_plural': '网站公告',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(default='...', max_length=30, verbose_name='ip')),
                ('location', models.CharField(default='', max_length=30, verbose_name='ip所在地')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间')),
                ('is_lock', models.BooleanField(default=True, verbose_name='访问状态')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
        migrations.CreateModel(
            name='VideoCate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='视频', max_length=100, verbose_name='视频类别')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.extension_tools.models.video_upload_to, verbose_name='视频')),
                ('file_name', models.CharField(default='默认时评', max_length=100, verbose_name='视频名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('comment', models.CharField(max_length=100, verbose_name='备注说明')),
                ('file_cate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='extension_tools.videocate', verbose_name='视频分类')),
            ],
            options={
                'verbose_name': '视频上传',
                'verbose_name_plural': '视频上传',
            },
        ),
    ]
